version: "3"
services:
  app:
    restart: on-failure
    build: .
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "3000:3000"
    command: yarn run start
    volumes:
      - /usr/src/app/
      - /usr/src/app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"
  postgres:
    image: postgres:15.2
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: challenge
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
